#!/usr/bin/python3
#SPDX-FileCopyrightText: 2023  Hinata Sakuma s20c1707fh@chibakoudai.jp
#SPDX-License-Identifier: BSD-3-Clause

import sys

ans = 0
for line in sys.stdin:
    try:
        ans += int(line)
    except:
        ans += float(line)

print(ans)
